apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacm-instance
  namespace: argocd
spec:
  destination:
    namespace: open-cluster-management
    server: https://kubernetes.default.svc
  project: default
  retry:
    backoff:
      duration: 20s
      factor: 2
      maxDuration: 5m
    limit: 10
  source:
    path: rhacm-deploy/rhacm-instance/overlays/ha
    repoURL: https://github.com/sabre1041/rhacm-argocd
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
