apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: managed-argocd-namespaced
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - { key: argocd-namespaced, operator: In, values: ["true"] }
