apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd-server
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: argocd-server
    weight: 100
  wildcardPolicy: None